# Generated by Django 2.1.3 on 2020-08-25 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Release Year')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Rating')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration')),
                ('genres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Genres')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Director')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_info', models.CharField(choices=[('Not Watched', 'Not Watched'), ('Already Watched', 'Already Watched'), ('Add to Watch List', 'Add to Watch List')], max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
